######################################################################
##
## Filename: Regs.udo
## Created on: Wed Feb 22 10:21:40 Hora estándar romance 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
