######################################################################
##
## Filename: AluMIPS.udo
## Created on: Wed Mar 08 10:59:00 Hora estándar romance 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
