######################################################################
##
## Filename: UnidadControlTb.udo
## Created on: Wed Apr 05 10:10:10 Hora de verano romance 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
